// AP World History: Modern Configuration
// Generated from top_200_exam_universe_seed.csv

export const EXAM_CONFIG = {
  examId: "EXAM182",
  slug: "ap-world-history-modern",
  name: "AP World History: Modern",
  fullName: "AP World",
  alias: "AP World",
  family: "AP",
  category: "School exams",
  subcategory: "AP subject exam",
  country: "United States",
  region: "North America",
  languages: ["English"],
  estimatedAnnualTakers: "high",
  testingWindow: "May",
  schedulePattern: "Annual",
  ageGroup: "15-19",
  targetUser: "AP student",
  delivery: "Paper/digital mix",
  questionTypes: ["MCQ","SAQ","DBQ","LEQ"],
  adaptivity: "Linear",
  sections: "Single subject",
  scoringMode: "1-5",
  essayOrSpeaking: "Essay",
  ipRisk: "High",
  contentReuse: "history_civics",
  uiEngine: "mixed_objective_essay",
  monetizationPotential: "High",
  tier: "Tier 4",
  launchWave: "Wave 6",
  themeColor: "#D97706",
  themeColorDark: "#B45309",
  localizationComplexity: "Low",
  offlineNeeded: false,
  mobileFirst: true,
  locale: "en",
  isRTL: false,
  freemiumGate: {
    dailyQuestions: 10,
  },
} as const;

export type ExamConfig = typeof EXAM_CONFIG;
